### ISSUE TITLE
Parametrisation of each Pokemon

### ISSUE THREAD

**Issue by simibac** [PokeMate/backend#1]
## User Story
As a user, I want to see detailed information about every Pokemon that exists so that I can study their fetishes, attractiveness, fertility and no-gos when it comes to mating partners.

## Description
We are using the given Pokemon data set https://www.kaggle.com/abcsds/pokemon as well as www.pokeapi.co for additional stats such as:
- weight
- evolution status (if a Pokemon is still a baby etc can be retrieved) https://pokeapi.co/docs/v2.html/#evolution-section

Each Pokemon receive randomised data for the following parameters when the application is initialised:
- fetish: "Likes slimy Pokemons". These tags are generated from a list of strings and don't really affect the mating algorithm.
- attractiveness: Based on if Legendary and the sum of attack, defense, etc (already part of the dataset)
- fertility: Depends on Pokemons Generation and Evolution status (can be retrieved from PokeAPI)
- preferred types: Each Pokemon has at least on type. To which other type a Pokemon is attracted to is purely randomised. 
- no-gos types: Which type is a turn-off for a Pokomen is purley randomised.

## Tasks
- [x] generate list of (funny) fetishes such as "Likes slimy Pokemons"
- [x] generate list of (funny) date outcome sentences such as "Pickatchu was too intrusive. No match!"
- [x] parse data set
- [x] incorporate pokeapi.co

When the application is initialised, the following are set for each Pokemon:
- [x] **fetish** _list of strings_: ["Likes, slimy Pokemons"]
- [x] **attractiveness** _float between 0..1_
- [x] **fertility** _float between 0..1_
- [x] **preferred types** _list of Pokemon types_: ["Grass", "Poison"]
- [x] **no-go types** _list of Pokemon types_: ["Grass", "Poison"]
