### ISSUE TITLE
Define API Specifications

### ISSUE THREAD

**Issue by simibac** [PokeMate/backend#16]
## User Story
As a frontend developer, I want to have a wiki with detailed information about the exposed endpoints by the Pokemate backend so that I know how to retrieve data and which parameters need to be sent.

## Description
This documentation in the wiki helps to keep track of which endpoints exist and how they can be accessed.

## Tasks
- [x] endpoints defined in wiki
- [x] approved by @Lochindaal 
- [x] add each endpoint as a separate feature request as an issue
