### ISSUE TITLE
maintain backend documentation

### ISSUE THREAD

**Issue by simibac** [PokeMate/backend#2]
## User Story
As a developer, I want to have a wiki with detailed information about the setup instructions of the backend application so that the project can be cloned and deployed on a different machine.

## Description
- The readme explains briefly how the application has to be connected to the DB, can be installed and deployed
- The wiki informs the people similar to the readme but in an extended form, such as the different models used, available endpoints etc.

## Tasks
- [ ] readme: instructions for setting up the environment
- [ ] readme: instructions for building and running the application
- [ ] readme: instructions for running the tests
- [ ] wiki: explanations of the parametrisation for each Pokemon (fetish, attractiveness, fertility, etc)
- [ ] .gitignore
