### ISSUE TITLE
Rating for generated name and image

### ISSUE THREAD

**Issue by simibac** [PokeMate/backend#3]
## User Stories
- As a researcher, I want to be able to train the machine learning models used by the platform continuously by adding new training material from the users and their ratings of the generated data from the machine learning predictions.
- As a researcher, I want a crowd-based machine learning platform with semi-labeled data.

## Description
When a new Pokemon is generated, a name is generated from [this random name generator service](https://github.com/PokeMate/name-generator) and a image from [this image generator service](https://github.com/PokeMate/image-generator). These names and images are produced by GANs and might not be perfectly suitable for a Pokemon. Thus, the user can rate the newly assigned name and image. 

This data will be used to improve the algorithm. A feature will allow to directly download the labeled data for other projects as a csv file.

## Tasks
- [ ] database model for a rating
- [ ] POST-endpoint for submitting a rating
- [ ] GET-endpoint for reading a rating
- [ ] logic for creating a .csv file with the generated names and images
- [ ] GET-endpoint for exporting the .csv file
- [ ] wiki: instructions on how the rating system works
- [ ] tests
