### ISSUE TITLE
PokeDex endpoint

### ISSUE THREAD

**Issue by simibac** [PokeMate/backend#4]
## User Story
As a user, I want to see all available Pokemons from the PokeDex so that I can see which and how many Pokemons exist.

## Description
Exposing [this data set](https://www.kaggle.com/abcsds/pokemon) through a REST interface. Add filter and search options.

`GET /pokemons?name=<name>&limit=<limit>&generations=<gen1>,<gen2>&types=<grass>,<poison>,<fire>&owned=<owned>`

List of pokemons that can be filtered with the following parameters.

| Parameter     | Type       | Required | Default Value | Description                                      |
| ------------- | ---------- | -------- | ------------- | ------------------------------------------------ |
| `name`        | `string`   | `no`     | `''`          | search string for pokemon name                   |
| `limit`       | `int`      | `no`     | `100`         | limit number of Pokemons                         |
| `generations` | `[string]` | `no`     | `[]`          | list or generations                              |
| `types`       | `[string]` | `no`     | `[]`          | list or pokemon types                            |
| `owned_by`    | `string`   | `no`     | `''`          | id of user to only show the pokemons a user owns |

## Tasks
- [x] parse Kaggle dataset
- [x] db model 
- [x] GET-enpoint
- [x] default sorting by Pokemon id
- [x] Test the endpoint
- [ ] Integrate Swagger

search by:
- [ ] name
- [x] type
- [ ] fetish

filter by:
- [x] generation [1-6, X]
- [x] types ["Grass"]
- [ ] part of collection

**Comment by simibac** [comment]
Maybe we don't need an additional endpoint for the users collection. We can use the PokeDex endpoint with an additional parameter which allows to query only the Pokemons from the PokeDex which are part of the collection.
